# Generated by Django 3.2.14 on 2022-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goal',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sourceincome',
            name='currency',
            field=models.CharField(default='', max_length=255),
        ),
    ]
