# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20220708_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='amount',
            new_name='added_amount',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='sourceincome',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='spent_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='display_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logsapi',
            name='request_parameter',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='sourceincome',
            name='display_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourceincome',
            name='spent_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='modified_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribed', to='Account.Subscription'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='min_pass_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Account.Tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='setup_count',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
