# Generated by Django 3.2.14 on 2022-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20220817_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_transaction',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
    ]
