# Generated by Django 3.2.14 on 2022-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_transaction_converted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AlterField(
            model_name='notification',
            name='android_r_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ios_r_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
