# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20220712_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='display_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sourceincome',
            old_name='display_amount',
            new_name='amount',
        ),
    ]
