# Generated by Django 3.2.14 on 2022-08-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
