# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-13 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_transaction_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 7, 13)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_at',
            field=models.DateField(default=datetime.date(2022, 7, 13)),
        ),
    ]
