# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-15 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_auto_20220713_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_partial_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_limit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='added_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sourceincome',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
    ]
