# Generated by Django 3.2.14 on 2022-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
