# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_auto_20220715_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='Account.Debt'),
        ),
    ]
