# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_goal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodic',
            name='status_days',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='periodic',
            name='week_days',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
