# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_auto_20220717_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, default='', max_length=15000, null=True),
        ),
    ]
